---


- hosts: all
  become: true
  become_method: su

  vars_files:
    - vars/defaults.yml
    - vars/{{ machine }}.yml

  vars_prompt:
    - name: keepass_psw
      prompt: "Enter keepass database password"
      private: yes

  tasks:
    - name: Execute Install
      include_tasks: tasks/install.yml

    - name: Configure Security
      include_tasks: tasks/security/_security.yml

    - name: Configure Trust Relationships
      include_tasks: tasks/trust-relationship.yml
      loop: "{{ trustRelationships }}"
      loop_control:
        loop_var: relationship

    - name: Initialize backup jobs
      set_fact:
        backup_jobs: []

    - name: Configure Storage Backups
      include_tasks: tasks/storage_backup.yml
      loop: "{{ storage_backups }}"
      loop_control:
        loop_var: backup

    - name: Create backup target directory
      file:
        path: "/backups/bin"
        state: directory

    - name: Create backup target directory
      file:
        path: "/backups/logs"
        state: directory

    - name: Register Storage Backup Scripts
      ansible.builtin.template:
        src: templates/backups/bin/backup.sh.j2
        dest: /backups/bin/{{ backup.name }}.sh
        owner: root
        group: root
        mode: u=rwx,g=r,o=r
      loop: "{{ backup_jobs }}"
      loop_control:
        loop_var: backup

    - name: Register Storage Backups
      ansible.builtin.template:
        src: templates/etc/systemd/system/backup.service.j2
        dest: /etc/systemd/system/backup-{{ backup.name }}.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      loop: "{{ backup_jobs }}"
      loop_control:
        loop_var: backup

    - name: Enable backup for autostart
      ansible.builtin.command: systemctl enable backup-{{ backup.name }}
      loop: "{{ backup_jobs }}"
      loop_control:
        loop_var: backup

    - name: Restart System Daemon
      ansible.builtin.command: systemctl daemon-reload

    - name: Configure VirtualBox and Machines
      include_tasks: tasks/virtual-box/_virtual-box.yml

    - name: Configure Mail Relay
      include_tasks: tasks/mail/postfix.yml