---


- hosts: all
  become: true
  become_method: su

  vars_files:
    - vars/defaults.yml
    - vars/{{ machine }}.yml

  vars_prompt:
    - name: keepass_psw
      prompt: "Enter keepass database password"
      private: yes

  tasks:
    - name: Execute Install
      include_tasks: tasks/install.yml

    - name: Configure Security
      include_tasks: tasks/security/_security.yml

    - name: Configure Trust Relationships
      include_tasks: tasks/trust-relationship.yml
      loop: "{{ trustRelationships }}"
      loop_control:
        loop_var: relationship

    - name: Initialize backup jobs
      set_fact:
        backup_jobs: []

    - name: Configure Storage Backups
      include_tasks: tasks/storage_backup.yml
      loop: "{{ storage_backups }}"
      loop_control:
        loop_var: backup

    - name: Register Storage Backups
      ansible.builtin.template:
        src: templates/etc/anacrontab.j2
        dest: /etc/anacrontab
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Configure VirtualBox and Machines
      include_tasks: tasks/virtual-box/_virtual-box.yml

    - name: Configure Mail Relay
      include_tasks: tasks/mail/postfix.yml