---

- name: Check if key exists
  stat:
    path: "/root/.ssh/id_ed25519"
  register: key_file

- name: Create SSH Key
  ansible.builtin.command: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ''
  when: key_file.stat.exists == False