---

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Add sudoers users to wheel group
  user:
    name={{item}}
    groups=sudo
    append=yes
    state=present
    createhome=yes
  loop: "{{ sudo_users }}"
