---
- name: Register Service {{ service.name }}
  ansible.builtin.template:
    src: templates/etc/systemd/system/a.service.j2
    dest: /etc/systemd/system/{{ service.name }}.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable backup for autostart
  ansible.builtin.command: systemctl enable {{ service.name }}

- name: Restart System Daemon
  ansible.builtin.command: systemctl daemon-reload